default: &default
  adapter: postgresql
  encoding: unicode
  username: d2ndjim
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vacci_test_development

  
test:
  <<: *default
  database: vacci_test_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>